# Generated by Django 3.1.4 on 2021-01-26 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название аэропорта')),
                ('iata_code', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Сокращеное имя по ИАТА')),
            ],
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Часть света')),
                ('url', models.SlugField(unique=True, verbose_name='Continent url')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Страна')),
                ('url', models.SlugField(verbose_name='Country url')),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='countries', to='ski.continent', verbose_name='Часть света')),
            ],
        ),
        migrations.CreateModel(
            name='Resort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Курорт')),
                ('skipass_price', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Цена скипасса')),
                ('bottom_point', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Нижняя точка')),
                ('top_point', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Верхняя точка')),
                ('url', models.SlugField(unique=True, verbose_name='Resort url')),
                ('country', models.ManyToManyField(related_name='resorts', to='ski.Country', verbose_name='Сатраны')),
            ],
        ),
        migrations.CreateModel(
            name='Slope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('green_slopes', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Протяжённость зелёных трасс')),
                ('blue_slopes', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Протяжённость синих трасс')),
                ('red_slopes', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Протяжённость красных трасс')),
                ('black_slopes', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Протяжённость чёрных трасс')),
                ('resort', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slopes', to='ski.resort', verbose_name='Курорт')),
            ],
        ),
        migrations.CreateModel(
            name='Lift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gondola_tram', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество гондол')),
                ('chairs', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Кресельные подъемники')),
                ('surface', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Бугели')),
                ('resort', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lifts', to='ski.resort', verbose_name='Курорт')),
            ],
        ),
        migrations.CreateModel(
            name='AirportDistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.PositiveSmallIntegerField(verbose_name='Расстояние от аэропорта до курорта')),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distances', to='ski.airport', verbose_name='Аэропорт')),
                ('resort', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='airport_distances', to='ski.resort', verbose_name='Куррорт')),
            ],
        ),
        migrations.AddField(
            model_name='airport',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='airports', to='ski.country', verbose_name='Страна аэропорта'),
        ),
    ]
