# Generated by Django 3.1.4 on 2021-01-26 18:31

from django.db import migrations
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('ski', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resort',
            options={'ordering': [django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.F('slopes__blue_slope'), '+', django.db.models.expressions.F('slopes__red_slopes')), '+', django.db.models.expressions.F('slopes__black_slopes'))]},
        ),
    ]
