# Generated by Django 3.1.5 on 2021-01-28 19:11

from django.db import migrations, models
import ski.models


class Migration(migrations.Migration):

    dependencies = [
        ('ski', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=ski.models.short_uuid, editable=False, unique=True)),
            ],
        ),
    ]
