# Generated by Django 3.1.5 on 2021-01-28 19:16

from django.db import migrations, models
import ski.models


class Migration(migrations.Migration):

    dependencies = [
        ('ski', '0002_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='uuid',
            field=models.CharField(default=ski.models.short_uuid, editable=False, max_length=16, unique=True),
        ),
    ]
