# Generated by Django 3.1.5 on 2021-01-28 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ski', '0003_auto_20210128_2216'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
