# Generated by Django 3.1.4 on 2021-01-26 18:39

from django.db import migrations
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('ski', '0003_auto_20210126_2137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resort',
            options={'ordering': [django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.F('slopes__blue_slopes'), '+', django.db.models.expressions.F('slopes__red_slopes')), '+', django.db.models.expressions.F('slopes__black_slopes')), '*', django.db.models.expressions.Value(-1))]},
        ),
    ]
