# Generated by Django 3.1.5 on 2021-01-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ski', '0005_auto_20210128_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continent',
            name='url',
            field=models.SlugField(max_length=250, unique=True, verbose_name='Continent url'),
        ),
        migrations.AlterField(
            model_name='country',
            name='url',
            field=models.SlugField(max_length=250, verbose_name='Country url'),
        ),
        migrations.AlterField(
            model_name='resort',
            name='url',
            field=models.SlugField(max_length=250, unique=True, verbose_name='Resort url'),
        ),
    ]
