# Generated by Django 3.1.4 on 2021-01-26 18:58

from django.db import migrations
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('ski', '0005_auto_20210126_2141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airport',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='continent',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='slope',
            options={'ordering': [django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.F('blue_slopes'), '*', django.db.models.expressions.Value(-1)), '-', django.db.models.expressions.F('red_slopes')), '-', django.db.models.expressions.F('black_slopes'))]},
        ),
    ]
