# Generated by Django 3.1.5 on 2021-01-29 11:25

from django.db import migrations, models

import ski.models


class Migration(migrations.Migration):

    dependencies = [
        ("ski", "0006_auto_20210128_2245"),
    ]

    operations = [
        migrations.AddField(
            model_name="continent",
            name="uuid",
            field=models.CharField(
                default=ski.models.short_uuid,
                editable=False,
                max_length=16,
                null=True,
                verbose_name="Уникальное имя (16 бит)",
            ),
        ),
        migrations.AddField(
            model_name="country",
            name="uuid",
            field=models.CharField(
                default=ski.models.short_uuid,
                editable=False,
                max_length=16,
                null=True,
                verbose_name="Уникальное имя (16 бит)",
            ),
        ),
    ]
