# Generated by Django 3.1.5 on 2021-01-29 11:25

import uuid
from typing import Counter

from django.db import migrations


def gen_uuid(apps, schema_editor):
    Continent = apps.get_model("ski", "Continent")
    Country = apps.get_model("ski", "Country")
    for row in Continent.objects.all():
        row.uuid = uuid.uuid4().hex[:16]
        row.save(update_fields=["uuid"])
    for row in Country.objects.all():
        row.uuid = uuid.uuid4().hex[:16]
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("ski", "0007_auto_20210129_1425"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
