# Generated by Django 3.1.4 on 2021-01-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.PositiveIntegerField(unique=True)),
                ('is_bot', models.BooleanField()),
                ('first_name', models.CharField(max_length=50)),
            ],
        ),
    ]
