# Generated by Django 3.1.5 on 2021-01-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ski', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.PositiveIntegerField(unique=True)),
                ('is_bot', models.BooleanField()),
                ('first_name', models.CharField(max_length=50)),
                ('bookmarks', models.ManyToManyField(related_name='followers', to='ski.Resort', verbose_name='Закладки пользователя')),
            ],
        ),
    ]
