# Generated by Django 3.1.4 on 2021-01-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ski', '0001_initial'),
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bookmarks',
            field=models.ManyToManyField(related_name='followers', to='ski.Resort', verbose_name='Закладки пользователя'),
        ),
    ]
